# Getting Started with pandas

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## Introduction to pandas Data Structures

### Series

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
obj2.index

d    4
b    7
a   -5
c    3
dtype: int64

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
#ลองเอง
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [11]:
#ลองเอง #search #ใช้ numpy array for indexing
import numpy as np
obj2[np.array([True, True, False, True])]

d    6
b    7
c    3
dtype: int64

In [12]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping
of index values to data values. It can be used in many contexts where you might
use a dict:

In [14]:
print('b' in obj2)
'e' in obj2

True

False

In [15]:
#ลองเอง #search
for i in obj2:
    print(i)
print()

for i in obj2.index:
    print(i, obj2[i])

6
7
-5
3

d 6
b 7
a -5
c 3

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

เข้าใจว่า ลำดับการแสดงผลจะเป็นไปตามลำดับของ label ที่ใส่เข้ามาใน argument index=... ส่วน value ที่ตรงกับ label l จะเป็น dict[l] <br/>
since no value for 'California' was found, it appears as `NaN` (not a number), which is considered
in pandas to mark missing or NA values.

the terms “missing” or “NA” interchangeably to refer to missing data. The
`isnull` and `notnull` functions in pandas should be used to detect missing data:

In [18]:
print(pd.isnull(obj4))
pd.notnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index
label in arithmetic operations:

In [20]:
print(obj3,'\n')
print(obj4)
obj3 + obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
print(obj)
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

0    4
1    7
2   -5
3    3
dtype: int64

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

The DataFrame has both a row and column index; it can be thought of
as a dict of Series all sharing the same index.

There are many ways to construct a DataFrame, though one of the most common is
from a dict of equal-length lists or NumPy arrays

In [7]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [24]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order:

In [26]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [11]:
#ลองเอง #list_of_rows
list_of_col = [data['year'],
             data['state'],
             data['pop']]
print(list_of_col, '\n')

list_of_row = zip(*list_of_col)
nrow = len(data['year'])
for _ in range(nrow):
    print(next(list_of_row))

print()
# Alternatively. 
# วิธีคิดก็คือถ้าเราใส่ arg ของ pd.DataFrame เป็นลิสต์แล้วละก็ item แรก จะไปปรากฎเป็น row 1 ใน data frame
# ถ้าเราต้องการให้ row 1 เป็น data ที่มาจากสามคอลัมน์เราก็ต้องทำให้ data จากสามคอลัมน์มาปรากฎเป็น item แรกในลิสต์
# ซึ่งก็ทำได้โดยการใช้ zip
list_of_row = zip(data['year'], data['state'], data['pop'])
nrow = len(data['year'])
for _ in range(nrow):
    print(next(list_of_row))

[[2000, 2001, 2002, 2001, 2002, 2003], ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]]

(2000, 'Ohio', 1.5)
(2001, 'Ohio', 1.7)
(2002, 'Ohio', 3.6)
(2001, 'Nevada', 2.4)
(2002, 'Nevada', 2.9)
(2003, 'Nevada', 3.2)

(2000, 'Ohio', 1.5)
(2001, 'Ohio', 1.7)
(2002, 'Ohio', 3.6)
(2001, 'Nevada', 2.4)
(2002, 'Nevada', 2.9)
(2003, 'Nevada', 3.2)

In [28]:
#ลองเอง #search #google-ai
#สร้าง pd จาก nested list. 
# Here, column names appears for the first time in argument 'columns', 
# which now do more than just telling us in what order we want column names to appear. 
# It does tell us the what are column names, which we didn't already know 
# because this information isn't included in the nested list.
# ===หมายเหตุ=== 
# สิ่งที่ต้องระวังคือ ใน nested list ม้นไม่บอกว่า array ตัวนึงมาจากชื่อคอลัมน์อะไร ดังนั้น order จึงสำคัญ 
# ต้องวางให้ตรงกับ order ใน argument 'columns'

df = pd.DataFrame(zip(*list_of_col), columns=['year', 'state', 'pop'])
df

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [225]:
#search
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
print(frame2)
frame2.columns

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [226]:
print(frame2['state'])
frame2.year

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Note that the returned Series have the same index as the DataFrame, and their name
attribute has been appropriately set.

In [227]:
#ลองเอง
try:
    frame2['random']
except KeyError:
    print('ERROR!')

ERROR!

In [228]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
#ลองเอง
try:
    frame2[['two','six']]
except KeyError:
    print('Error found')
    print(frame2.loc[['two','six']])

Error found
     year   state  pop debt
two  2001    Ohio  1.7  NaN
six  2003  Nevada  3.2  NaN

In [229]:
frame2['debt'] = 16.5
frame2
frame2['debt'] = np.arange(6.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame.

If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any holes:

In [231]:
#missing #assignseries
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2['new'] = val*val
frame2

       year   state  pop  debt   new
one    2000    Ohio  1.5   NaN   NaN
two    2001    Ohio  1.7  -1.2  1.44
three  2002    Ohio  3.6   NaN   NaN
four   2001  Nevada  2.4  -1.5  2.25
five   2002  Nevada  2.9  -1.7  2.89
six    2003  Nevada  3.2   NaN   NaN

In [36]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2
#From book: New columns cannot be created with the frame2.eastern syntax.

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [37]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

The column returned from indexing a DataFrame is a view on the
underlying data, not a copy. Thus, any in-place modifications to the
Series will be reflected in the DataFrame. The column can be
explicitly copied with the Series’s `copy` method.

In [38]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [39]:
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [40]:
print(frame3.index)
frame3.Nevada.index

Int64Index([2001, 2002, 2000], dtype='int64')

Int64Index([2001, 2002, 2000], dtype='int64')

In [41]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

The keys in the inner dicts are combined and sorted to form the index in the result.
This isn’t true if an explicit index is specified:

In [42]:
pd.DataFrame(pop, index=[2003, 2001, 2002])

      Nevada  Ohio
2003     NaN   NaN
2001     2.4   1.7
2002     2.9   3.6

In [43]:
#ลองเอง
# ดูเหมือนว่า มันจะไล่ตามลำดับ key ที่ปรากฎใน inner dict ตัวแรกก่อน แล้วค่อยไปยังตัวที่สอง
pop2 = {'Nevada': {2002: 2.4, 2000: 2.9},
       'Ohio': {2001: 1.5, 2000: 1.7, 2002: 3.6}}
pd.DataFrame(pop2)

      Nevada  Ohio
2002     2.4   3.6
2000     2.9   1.7
2001     NaN   1.5

Dict of Series

In [44]:
print(frame3['Ohio'])
print(frame3['Ohio'][:-1])

print('\n')

print(frame3['Nevada'])
print(frame3['Nevada'][:2])

pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64
2001    1.7
2002    3.6
Name: Ohio, dtype: float64


2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64
2001    2.4
2002    2.9
Name: Nevada, dtype: float64

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [45]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [46]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [47]:
print(frame2)
frame2.values

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

![](chan_folder/df_constructor.png)

In [48]:
#ลองเอง สร้าง list of dicts
# each element of the list corresponds to a 'row'
pd.DataFrame([
    {'Nevada': 3.14, 'Ohio':4.13}, # row 1
    {'Texas': 2.718, 'Nevada': 8.712} # row 2
], index=['PI','E'])

    Nevada  Ohio  Texas
PI   3.140  4.13    NaN
E    8.712   NaN  2.718

### Index Objects

In [49]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

index[1] = 'd'  # TypeError

In [50]:
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2)
obj2.index is labels

0    1.5
1   -2.5
2    0.0
dtype: float64

True

In [51]:
print(frame3)
print(frame3.columns, '\n')

print('Ohio' in frame3.columns)
print(2003 in frame3.index)
print(2002 in frame3.index)

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5
Index(['Nevada', 'Ohio'], dtype='object', name='state')

True
False
True

In [52]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [53]:
#ลองเอง
dup_arr = np.arange(12).reshape((4, 3))
dup_frame = pd.DataFrame(dup_arr, columns = [f'class ({i})' for i in range(3)], index = dup_labels)
print(dup_frame)

     class (0)  class (1)  class (2)
foo          0          1          2
foo          3          4          5
bar          6          7          8
bar          9         10         11

In [54]:
#ลองเอง
print(dup_frame.loc['bar'])
print(dup_frame.loc[['bar', 'foo']]) #สังเกต order ว่า foo มาหลัง bar ในผลลัพธ์

     class (0)  class (1)  class (2)
bar          6          7          8
bar          9         10         11
     class (0)  class (1)  class (2)
bar          6          7          8
bar          9         10         11
foo          0          1          2
foo          3          4          5

In [55]:
#ลองเอง
dup_frame2 = pd.DataFrame(dup_arr, columns = [f'class ({i})' for i in range(3)], index = ['foo', 'foo', 'bar', 'bar'])
print(dup_frame2)

     class (0)  class (1)  class (2)
foo          0          1          2
foo          3          4          5
bar          6          7          8
bar          9         10         11

In [56]:
#ลองเอง
print(dup_frame2.loc['bar'])
print(dup_frame2.loc[['bar', 'foo']]) #สังเกต order ว่า foo มาหลัง bar ในผลลัพธ์

     class (0)  class (1)  class (2)
bar          6          7          8
bar          9         10         11
     class (0)  class (1)  class (2)
bar          6          7          8
bar          9         10         11
foo          0          1          2
foo          3          4          5

In [143]:
#ลองเอง
dup_frame3 = pd.DataFrame(dup_arr, columns = [f'class ({i})' for i in range(3)], index = ['foo', 'foo', 'bar', 'baz'])
print(dup_frame3)

     class (0)  class (1)  class (2)
foo          0          1          2
foo          3          4          5
bar          6          7          8
baz          9         10         11

In [174]:
#ลองเอง #lower
# Just to remind myself that normally putting a single element inside of [] will produce a lower-dimension object.
print(dup_frame3.loc['bar'])
print(dup_frame3.loc[['bar', 'foo']]) #สังเกต order ว่า foo มาหลัง bar ในผลลัพธ์

class (0)    6
class (1)    7
class (2)    8
Name: bar, dtype: int32
     class (0)  class (1)  class (2)
bar          6          7          8
foo          0          1          2
foo          3          4          5

In [186]:
print(dup_frame3.loc['bar', 'class (0)'], '\n')
print(dup_frame3.loc['bar', ['class (0)']], '\n') # dimension ที่ contain 'class (0)' ไม่ collapse (คิดคล้ายๆว่า มีหลายๆ class)
print(dup_frame3.loc[['bar'], 'class (0)'], '\n') # dimension ที่ contain 'bar' ไม่ collapse
print(dup_frame3.loc[['bar'], ['class (0)']], '\n')

6

class (0)    6
Name: bar, dtype: int32

bar    6
Name: class (0), dtype: int32

     class (0)
bar          6

## Essential Functionality

### Reindexing

In [57]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [58]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [59]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
obj3.reindex(range(6), method='ffill')

0      blue
2    purple
4    yellow
dtype: object

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter either the (row) index, columns, or both. **When
passed only a sequence**, it reindexes the rows in the result:

In [60]:
#default
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
print(frame)
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [61]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [62]:
#frame.loc[['a', 'b', 'c', 'd'], states]
frame.loc[['d', 'c'], ['California', 'Texas', 'Ohio']]

   California  Texas  Ohio
d           8      7     6
c           5      4     3

### Dropping Entries from an Axis

In [63]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj
new_obj = obj.drop('c')
print(new_obj)
obj.drop(['d', 'c'])

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

In [64]:
#ลองเอง #view

# new_obj isn't a view of obj
print(obj)
new_obj[0] = '-1'
print(new_obj)
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a   -1.0
b    1.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [65]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [67]:
data.drop('two', axis=1)
data.drop(['two', 'four'], axis='columns')

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [68]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [69]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj
obj['b']
obj[1]
obj[2:4] # เอาตัวที่สามถึงสี่(5 excluded)
obj[['b', 'a', 'd']]
obj[[1, 3]]
obj[obj < 2] # เคยลองแล้วด้านบน

a    0.0
b    1.0
dtype: float64

In [70]:
#ลองเอง #search
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

print(obj < 2)

print(obj[np.array([True, True, False, False])])

bool_serie1 = pd.Series({'a': True, 'b': True, 'c': False, 'd': False})
print(obj[bool_serie1])

bool_serie2 = pd.Series({'a': False, 'b': True, 'c': False, 'd': True})
print(obj[bool_serie2])

a     True
b     True
c    False
d    False
dtype: bool
a    0.0
b    1.0
dtype: float64
a    0.0
b    1.0
dtype: float64
b    1.0
d    3.0
dtype: float64

Slicing with labels behaves differently than normal Python slicing in that the endpoint
is inclusive:

In [71]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [72]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [73]:
#ลองเอง #view
obj_slice = obj['b':'c']
obj_slice[0] *= 10
obj

a     0.0
b    50.0
c     5.0
d     3.0
dtype: float64

Indexing ใน data frame ปกติจะเป็นการเลือก column

In [5]:
#search
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data, '\n')
print(data['two'])
print(data[['two']], '\n')
print(data[['three', 'one']])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
          two
Ohio        1
Colorado    5
Utah        9
New York   13

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

**Special cases:** slicing or selecting data with a boolean
array:

In [75]:
print(data[:2])
print(data[data['three'] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
idx  = data['three'] > 5
print(isinstance(idx, pd.Series))
print(idx, '\n')

print(data[np.array([False, True, True, True])])

bool_serie3 = pd.Series({'Colorado': False, 'New York': True, 'Utah': False, 'Ohio': True})
print(data[bool_serie3])

True
Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

C:\Users\Lenovo\miniconda3\envs\4book\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

Another use case is in indexing with a boolean DataFrame, such as one produced by a
scalar comparison:

In [77]:
print(data < 5)
data[data < 5] = 0
data

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

This makes DataFrame syntactically more like a two-dimensional NumPy array in
this particular case.

#### Selection with loc and iloc

In [78]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [79]:
#ลองเอง #lower
data.loc['Colorado':'Colorado', ['two', 'three']] # Replace a single label with a slice to prevent lower dimension

          two  three
Colorado    5      6

In [80]:
#ลองเอง
data.loc[['New York', 'Colorado'], ['two', 'three']]

          two  three
New York   13     14
Colorado    5      6

In [81]:
data.values

array([[ 0,  0,  0,  0],
       [ 0,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [83]:
#ลองเอง
data.values[2, [3, 0, 1]]

array([11,  8,  9])

In [84]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [141]:
#ลองเอง
data.values[2]

array([ 8,  9, 10, 11])

In [142]:
#ลองเอง
data.values[2, :]

array([ 8,  9, 10, 11])

In [86]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [87]:
#ลองเอง
data.values[[1, 2], [3, 0, 1]]
# fancy indexing do not allow incompatible shapes

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,)

In [88]:
#ลองเอง
data.values[[1,2]][:, [3, 0, 1]]
# See #rectangular in chap 4

array([[ 7,  0,  5],
       [11,  8,  9]])

In [89]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [90]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [91]:
#ลองเอง
data.iloc[:, :3][pd.Series({'Ohio':False, 'Colorado': True, 'Utah': True, 'New York': True})]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [92]:
bools = [False, True, True, True] 
print(data.index)

d1 = {state: flag for state, flag in zip(data.index, bools)}
d2 = dict(zip(data.index, bools))

print(d1)
print(d2)

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')
{'Ohio': False, 'Colorado': True, 'Utah': True, 'New York': True}
{'Ohio': False, 'Colorado': True, 'Utah': True, 'New York': True}

### Integer Indexes

ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [93]:
ser = pd.Series(np.arange(3.))
ser[-1] #มันเข้าใจว่า -1 คือ label-based ไม่ใช่ position-based

KeyError: -1

In [94]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [95]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1] # with a non-integer index, there is no potential for ambiguity

2.0

In [96]:
ser[:1]

0    0.0
dtype: float64

In [97]:
ser.loc[:1] # 1 คือ label ซึ่ง the endpoint is inclusive

0    0.0
1    1.0
dtype: float64

In [98]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

When you are adding together objects, if any
index pairs are not the same, the respective index in the result will be the union of the
index pairs.

In [99]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [100]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In the case of DataFrame, alignment is performed on both the rows and the columns:

In [101]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [102]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [103]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)
df1 - df2

   A
0  1
1  2
   B
0  3
1  4

    A   B
0 NaN NaN
1 NaN NaN

In [104]:
#ลองเอง
df123 = pd.DataFrame({'A':[10, 20]}) #เสมือนใส่ index = [0, 1]
print(df1 + df123)

df32 = pd.DataFrame({'A':[100, 150, 200]}, index = [2, 3, 1])
print(df123 + df32)

    A
0  11
1  22
       A
0    NaN
1  220.0
2    NaN
3    NaN

เฉพาะ index 1 ที่ overlap between `df32`, `df123`

#### Arithmetic methods with fill values

In [105]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [106]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [107]:
df1.add(df2, fill_value=1000)

        a       b       c       d       e
0     0.0     2.0     4.0     6.0  1004.0
1     9.0  1005.0    13.0    15.0  1009.0
2    18.0    20.0    22.0    24.0  1014.0
3  1015.0  1016.0  1017.0  1018.0  1019.0

สังเกต cell 1-b ด้วย...<br/>
fill_value จะเข้ามาแทนที่ ในสองเงื่อนไข
1. A cell is missing in one df
2. A cell contains NaN in one df

In [108]:
#ลองเอง 
#พบว่าถ้าตำแหน่งเดียวกันของสอง input เป็น NaN ทั้งคู่ จะไม่มีการ fill ที่ตำแหน่งนั้น

mydf1 = pd.DataFrame(np.arange(9).reshape((3, 3)), columns = ['a', 'b', 'c'])
mydf2 = pd.DataFrame(np.zeros((3,3)), columns = ['a', 'b', 'c'])

mydf1.iloc[1,1] = mydf2.iloc[2,1] = np.nan
print(mydf1)
print(mydf2)
print(mydf1.add(mydf2, fill_value=1000), '\n')

mydf1.iloc[0,0] = mydf2.iloc[0,0] = np.nan
print(mydf1)
print(mydf2)
print(mydf1.add(mydf2, fill_value=1000))

   a    b  c
0  0  1.0  2
1  3  NaN  5
2  6  7.0  8
     a    b    c
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  NaN  0.0
     a       b    c
0  0.0     1.0  2.0
1  3.0  1000.0  5.0
2  6.0  1007.0  8.0

     a    b  c
0  NaN  1.0  2
1  3.0  NaN  5
2  6.0  7.0  8
     a    b    c
0  NaN  0.0  0.0
1  0.0  0.0  0.0
2  0.0  NaN  0.0
     a       b    c
0  NaN     1.0  2.0
1  3.0  1000.0  5.0
2  6.0  1007.0  8.0

In [109]:
1 / df1
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [110]:
#ลองเอง
a = pd.DataFrame(np.zeros((3, 3))+10)
b = pd.DataFrame(np.zeros((3, 3))+2)

print(b.rsub(a))
print(a.sub(b), '\n')

print(a.div(b))
print(b.rdiv(a))

     0    1    2
0  8.0  8.0  8.0
1  8.0  8.0  8.0
2  8.0  8.0  8.0
     0    1    2
0  8.0  8.0  8.0
1  8.0  8.0  8.0
2  8.0  8.0  8.0

     0    1    2
0  5.0  5.0  5.0
1  5.0  5.0  5.0
2  5.0  5.0  5.0
     0    1    2
0  5.0  5.0  5.0
1  5.0  5.0  5.0
2  5.0  5.0  5.0

In [111]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [112]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0]) #can be broadcast to have shape == 1x4
arr - arr[0]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [113]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame)
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

By default, arithmetic between DataFrame and Series matches the index of the Series
on the DataFrame’s columns, **broadcasting down the rows**. ( serie ถูก pad ให้มี 1 row จากนั้น มันได้ถูกขยายไปเป็นหลายๆ rows)

In [114]:
#default
# Cell (X)
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [115]:
#ลองเอง
mean_series = pd.Series({'e': 6.5, 'b': 4.5, 'd': 5.5})
frame - mean_series

          b    d    e
Utah   -4.5 -4.5 -4.5
Ohio   -1.5 -1.5 -1.5
Texas   1.5  1.5  1.5
Oregon  4.5  4.5  4.5

If an index value is not found in either the DataFrame’s columns or the Series’s index,
the objects will be reindexed to form the union:

In [116]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

If you want to instead broadcast over the columns (จากเดิม `series3` มีแค่ 1 column ถูกขยายจนมี จ.น. column เท่ากับ `frame`), matching on the rows, you have to
use one of the arithmetic methods. The axis number that you pass is the axis to match on. In this case we mean to match
on the DataFrame’s row index (`axis='index'` or `axis=0`) and broadcast across.

ก็คือ การ duplicate in columns direction จะเกิดขึ้นได้ series ก็จะต้องถูกปรับให้เป็น column vector หลังจากนั้นมันก็จะถูกเอาไปบวก กับ column vector ที่มาจากแต่ละ column ของ frame (column vector ไม่สามารถบวกกับ row vector ได้ ดังนั้น serie จะต้องบวกกับ column เท่านั้น) และเนื่องจากแต่ละ column ใน frame ถูก label ด้วย index หลายๆ index การที่เราจะเอา series ไปบวกกับมัน เราจะต้อง match index

In [117]:
series3 = frame['d']
print(frame)
print(series3)
print(frame.sub(series3, axis='index'))
print(frame.sub(series3)) 
# By default, arithmetic between DataFrame and Series matches the index of the Series on the DataFrame’s columns

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64
          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0
        Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [118]:
frame.sub?

In [119]:
#ลองเอง #search
# ตรง cell (X) ข้างบน arithmetic ทำได้โดยที่ เราไม่สน Name ของ serie ว่าต้อง match กับ index ของ frame
# แต่ถ้าเป็น data frame ทั้งคู่จะไม่ได้หรือเปล่า
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame, "\n")
print('DataFrame:')
print(frame.loc[['Utah']], '\n')
print("Series:")
print(frame.loc['Utah'],'\n')

print(frame  - frame.loc[['Utah']])
print(frame  - frame.loc['Utah'])

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

DataFrame:
        b    d    e
Utah  0.0  1.0  2.0

Series:
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

          b    d    e
Ohio    NaN  NaN  NaN
Oregon  NaN  NaN  NaN
Texas   NaN  NaN  NaN
Utah    0.0  0.0  0.0
          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

### Function Application and Mapping

In [120]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)
print(frame)

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [121]:
f = lambda x: x.max()
frame.apply(f)

b    1.246435
d    1.965781
e    1.393406
dtype: float64

>Here the function `f`, which computes the maximum of a Series, is invoked once on each column in `frame`. 
**The result is a Series having the columns of `frame` as its index.**

ประโยคสุดท้ายตีความได้ว่า columns are retained

In [122]:
#ลองเอง #default
frame.apply(lambda x: x.max(), axis='index') 
# from doc: 0 or 'index': apply function to each column.
# invoke once per column --> the computation is performed across the whole index (or all rows) of "each column"
# Each value of the result belongs to each column and so it is labeld with the column name --> "columns are retained"

b    1.246435
d    1.965781
e    1.393406
dtype: float64

In [123]:
frame.apply?

If you pass `axis='columns'` to apply, the function will be invoked once per row
instead:

In [124]:
frame.apply(lambda x: x.max(), axis='columns')
# The computation is performed across all columns of "each row". 
# Each element of an output belongs to each row. We label it using the row's index label. --> rows are retained

Utah      0.478943
Ohio      1.965781
Texas     0.769023
Oregon    1.246435
dtype: float64

In [125]:
print(frame.max(axis='index'), '\n')
print(frame.max(axis='columns'))

b    1.246435
d    1.965781
e    1.393406
dtype: float64

Utah      0.478943
Ohio      1.965781
Texas     0.769023
Oregon    1.246435
dtype: float64

In [126]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)
# Per each column, each serie is returned.
#series #return

            b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [127]:
format = lambda x: '%.2f' % x
frame.applymap(format)

            b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [136]:
'%.3f %.2f' % (1, 2)

'1.000 2.00'

In [128]:
frame['e'].map(format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

### Sorting and Ranking

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

In [149]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
print(frame.sort_index(), '\n')
print(frame.sort_index(axis=0), '\n')
print(frame.sort_index(axis=1))

# ตรง reindex: When passed only a sequence, it reindexes the rows in the result:
# ตรงนี้: default behavior is to sort index (on rows)

# From doc
# axis : {0 or 'index', 1 or 'columns'}, default 0
#    The axis along which to sort.  The value 0 identifies the rows,
#    and 1 identifies the columns

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [150]:
frame.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [151]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

Any missing values are sorted to the end of the Series by default:

In [152]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [153]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(frame)
frame.sort_values(by='b')

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [154]:
frame.sort_values(by=['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

เพื่อทำความเข้าใจประโยคในหนังสือ
>by default rank
breaks ties by assigning each group the mean rank

> Here, instead of using the average rank 6.5 for the entries 0 and 2, they instead have
been set to 6 and 7 because label 0 precedes label 2 in the data.

จึงเขียน R code นี้ขึ้นมา
```
library(tidyverse)

df <- tibble(
  data=c(7, -5, 7, 4, 2, 0, 4),
  rank_method_first=c(6., 1., 7., 4., 3., 2., 5.)
  ) |> mutate(data = as.integer(data))

df

df |> group_by(data) |> 
      mutate(mean_rank = mean(rank_method_first)) |>
      print() |>
      mutate(mean_rank_format = scales::label_number(0.1)(mean_rank)) |>
      ungroup() |>
      select(last_col())

###### Output ######
  mean_rank_format
  <chr>           
1 6.5             
2 1.0             
3 6.5             
4 4.5             
5 3.0             
6 2.0             
7 4.5
```

In [155]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [160]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

>You can rank in descending order, too:

```
df1 <- tibble(
  data=c(7, -5, 7, 4, 2, 0, 4),
  method_first_desc=c(1., 7., 2., 3., 5., 6., 4.)
) |> mutate(data = as.integer(data))

df1 |> group_by(data) |> 
  mutate(max_rank = max(method_first_desc)) |>
  print() |>
  mutate(max_rank_format = scales::label_number(0.1)(max_rank)) |>
  ungroup() |>
  select(last_col())
  
###### Output ######
# A tibble: 7 × 1
  max_rank_format
  <chr>          
1 2.0            
2 7.0            
3 2.0            
4 4.0            
5 5.0            
6 6.0            
7 4.0
```

In [167]:
# Assign tie values the maximum rank in the group
print(obj.rank(ascending=False, method='first'))
obj.rank(ascending=False, method='max')

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [169]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
print(frame)
frame.rank(axis='columns')

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [170]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [171]:
obj.index.is_unique

False

In [172]:
obj['a']

a    0
a    1
dtype: int64

In [173]:
obj['c']

4

In [181]:
#ลองเอง #lower
obj[['c']] # dimension ที่ contain 'c' ไม่ collapse

c    4
dtype: int64

In [183]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
print(df)
df.loc['b']

          0         1         2
a -0.577087  0.124121  0.302614
a  0.523772  0.000940  1.343810
b -0.713544 -0.831154 -2.370232
b -1.860761 -0.860757  0.560145

          0         1         2
b -0.713544 -0.831154 -2.370232
b -1.860761 -0.860757  0.560145

## Summarizing and Computing Descriptive Statistics

In [187]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [188]:
df.sum() # across rows, columns are retained

one    9.25
two   -5.80
dtype: float64

In [189]:
df.sum(axis='columns') # across columns, rows are retained

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [191]:
df.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [192]:
df.idxmax() # เข้าใจว่า across rows, columns are retained

one    b
two    d
dtype: object

In [199]:
#ลองเอง
df_many_cols = pd.DataFrame({'col1': [1, 3], 'col2': [4, -1], 'col3': [0, 2], 'col4': [-2, -0.5]}) 
print(df_many_cols, '\n')
print(df_many_cols.idxmax(), '\n') # columns are retained
print(df_many_cols.idxmax(axis='index'), '\n') # columns are retained
print(df_many_cols.idxmax(axis='columns'), '\n') # row are retained

   col1  col2  col3  col4
0     1     4     0  -2.0
1     3    -1     2  -0.5

col1    1
col2    0
col3    1
col4    1
dtype: int64

col1    1
col2    0
col3    1
col4    1
dtype: int64

0    col2
1    col1
dtype: object

In [200]:
df.cumsum() # cumsum calculated across rows

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [202]:
print(df.mean(), '\n')
print(df.std(), '\n')
print(df.describe(), '\n')

one    3.083333
two   -2.900000
dtype: float64

one    3.493685
two    2.262742
dtype: float64

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [203]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [210]:
# ไม่เกี่ยวกับ section นี้ แค่ทดสอบเพื่อเปรียบเทียบกับ returns.MSFT ด้านล่าง
print(df.two)
print(df.one)

a    NaN
b   -4.5
c    NaN
d   -1.3
Name: two, dtype: float64
a    1.40
b    7.10
c     NaN
d    0.75
Name: one, dtype: float64

### Correlation and Covariance

conda install pandas-datareader

In [204]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

```
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})
```

In [207]:
returns = price.pct_change()
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

The `corr` method of Series computes the correlation of the overlapping, non-NA,
aligned-by-index values in two Series. Relatedly, `cov` computes the covariance:

In [212]:
returns['MSFT'].corr(returns['IBM'])

0.4997636114415114

In [213]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703546e-05

In [214]:
returns.MSFT.corr(returns.IBM)

0.4997636114415114

In [216]:
print(type(returns.MSFT))
print(type(returns))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [217]:
returns.corr()
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

Using DataFrame’s `corrwith` method, you can compute pairwise correlations
between a DataFrame’s columns or rows with another Series or DataFrame. Passing a
Series returns a Series with the correlation value computed for each column:

In [221]:
print(returns.corrwith(returns.IBM), '\n')

print(returns.IBM.corr(returns.AAPL))
print(returns.IBM.corr(returns.GOOG))
print(returns.IBM.corr(returns.MSFT))

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

0.38681743611391
0.40509941874156363
0.4997636114415114

Passing a DataFrame computes the correlations of **matching column names**. Here I
compute correlations of percent changes with volume:

In [224]:
print(returns.corrwith(volume),'\n')

print(returns.AAPL.corr(volume.AAPL))
print(returns.GOOG.corr(volume.GOOG))
print(returns.IBM.corr(volume.IBM))
print(returns.MSFT.corr(volume.MSFT))

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

-0.07556463594911404
-0.0070667470877580065
-0.20484942947042922
-0.0929503469381873

### Unique Values, Value Counts, and Membership

![](chan_folder/series_method.png)

In [232]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [233]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [234]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

The Series is sorted by value in descending order as a convenience.

In [235]:
# a top-level pandas method #sort=False
pd.value_counts(obj.values, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [236]:
pd.value_counts(obj, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [237]:
print(obj)
mask = obj.isin(['b', 'c'])
print(mask)
obj[mask] #สังเกต index ของ result ด้วย

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object
0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

0    c
5    b
6    b
7    c
8    c
dtype: object

`Index.get_indexer` method, which gives you an index array
from an array of possibly non-distinct values into another array of distinct values:

In [239]:
#level_in_R
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [240]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [241]:
result = data.apply(pd.value_counts).fillna(0)
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

Here, the row labels in the result are the distinct values occurring in all of the columns.
The values are the respective counts of these values in each column.

In [242]:
#ลองเอง
data.apply(pd.value_counts)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

## Conclusion

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS