What is the shortcut to convert a Jupyter cell to markdown?

Here are the steps to follow:
1. Click on the code cell that you want to convert to a markdown cell.
2. Press the Esc key to enter command mode.
3. Press the M key to convert the cell to a markdown cell. (ไม่ต้อง m ใหญ่ แค่ m เล็กก็พอ)

In [20]:
import numpy as np

# Play with keyword-arguments

In [3]:
# For completion of function keyword-arguments
def func_with_keywords(abra=1, abbra=2, abbbra=3):
    return abra, abbra, abbbra

In [3]:
func_with_keywords(abbbra=30)

(1, 2, 30)

In [4]:
func_with_keywords(abbra=200,10, 30)

SyntaxError: positional argument follows keyword argument (<ipython-input-4-a8cee65b9a2d>, line 1)

In [6]:
func_with_keywords(10, 30, abbra=200)

TypeError: func_with_keywords() got multiple values for argument 'abbra'

In [4]:
func_with_keywords(10, abbbra=30, abbra=200)

(10, 200, 30)

# Paste code from clipboard

In [7]:
%paste

UsageError: Line magic function `%paste` not found.

# Using magic

In [10]:
%whos

Variable             Type        Data/Info
------------------------------------------
func_with_keywords   function    <function func_with_keywo<...>ds at 0x0000023554FCF378>

In [11]:
foo = %pwd

In [12]:
print(foo)

C:\Users\Lenovo\Documents\Python\book\Python for Data Analysis\pydata-book

In [13]:
%pwd

'C:\\Users\\Lenovo\\Documents\\Python\\book\\Python for Data Analysis\\pydata-book'

In [47]:
'555\n555'

'555\n555'

In [49]:
'666\\n666'

'666\\n666'

In [40]:
print('555\n555')
print('666\\n666')

555
555
666\n666

In [53]:
print('555\n555'[2])
print('555\n555'[3])
print('555\n555'[4])

5


5

In [52]:
print('666\\n666'[2])
print('666\\n666'[3])
print('666\\n666'[4])

6
\
n

In [2]:
print('string')
'string'

string

'string'

# มาจาก บท 4

## Basic Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]

#As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated (or broadcasted henceforth) to the entire selection.
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
l = list(range(10))
l[5:8] = [12]
l

[0, 1, 2, 3, 4, 12, 8, 9]

## Boolean Indexing

In [6]:
a = 1; b = 2;
if (a == 1) & (b == 2):
    print('T & T')
if (a == 1) & (b == 0):
    print('T & F')
if (a == 0) & (b == 2):
    print('F & T')
if (a == 0) & (b == 0):
    print('F & F')

if (a == 1) | (b == 2):
    print('T | T')
if (a == 1) | (b == 0):
    print('T | F')
if (a == 0) | (b == 2):
    print('F | T')
if (a == 0) | (b == 0):
    print('F | F')

T & T
T | T
T | F
F | T

In [19]:
# ข้อควรระวังในการใช้ --> ต้องใส่วงเล็บ
if a == 9 & a == 1:
    print('F & T')
if  (a == 9) & (a == 1):
    print('(F) & (T)')

F & T

In [21]:
np.array([True, False]) | True

array([ True,  True])

In [22]:
np.array([True, False]) | False

array([ True, False])

In [23]:
np.logical_and(np.array([True, False]), False)

array([False, False])

## Array-Oriented Programming with Arrays

In [27]:
p = np.arange(0,1, 0.1)
print(p, len(p)) # ถ้า tick ไปถึง 1 len ก็จะเป็น 11

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] 10

In [29]:
points = np.arange(-5, 5, 0.01)
points[-3:] # tick วิ่งไม่ถึง 5

array([4.97, 4.98, 4.99])

# บท 7

In [4]:
import pandas as pd
import numpy as np
from numpy import nan as NA

## Filtering Out Missing Data

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
data[4] = NA

In [6]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [7]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

จะ reimplement ให้เหมือน cell ข้างบนโดยใช้ numpy.all

In [33]:
data_arr = data.values
flag = pd.isnull(data).values
mask = ~flag.all(axis=0)

ans01 = data_arr[:, mask]
print(ans01)

ans02 = data.loc[:, mask]
ans02

[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

## Scratchpad

In [14]:
flag

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [18]:
flag.all(axis=0)

array([False, False, False,  True])

In [20]:
mask

array([ True,  True,  True, False])

จากที่ลองเล่นใน chap 05 "selecting data with a boolean array" จะเป็นการเลือก row
![](df_bool_sel_row.png)

In [24]:
print(data_arr)
print(data_arr[:, mask])

[[1.  6.5 3.  nan]
 [1.  nan nan nan]
 [nan nan nan nan]
 [nan 6.5 3.  nan]]
[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]

In [32]:
data.loc[:, mask]
data.iloc[:, mask]

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0