What is the shortcut to convert a Jupyter cell to markdown?

Here are the steps to follow:
1. Click on the code cell that you want to convert to a markdown cell.
2. Press the Esc key to enter command mode.
3. Press the M key to convert the cell to a markdown cell. (ไม่ต้อง m ใหญ่ แค่ m เล็กก็พอ)

In [20]:
import numpy as np

# Play with keyword-arguments

Also see section 3.2 (Funciton) in ch03.ipynb

In [3]:
# For completion of function keyword-arguments
def func_with_keywords(abra=1, abbra=2, abbbra=3):
    return abra, abbra, abbbra

In [3]:
func_with_keywords(abbbra=30)

(1, 2, 30)

In [4]:
func_with_keywords(abbra=200,10, 30)

SyntaxError: positional argument follows keyword argument (<ipython-input-4-a8cee65b9a2d>, line 1)

In [6]:
func_with_keywords(10, 30, abbra=200)

TypeError: func_with_keywords() got multiple values for argument 'abbra'

In [4]:
func_with_keywords(10, abbbra=30, abbra=200)

(10, 200, 30)

# Paste code from clipboard

In [7]:
%paste

UsageError: Line magic function `%paste` not found.

# Using magic

In [10]:
%whos

Variable             Type        Data/Info
------------------------------------------
func_with_keywords   function    <function func_with_keywo<...>ds at 0x0000023554FCF378>

In [11]:
foo = %pwd

In [12]:
print(foo)

C:\Users\Lenovo\Documents\Python\book\Python for Data Analysis\pydata-book

In [13]:
%pwd

'C:\\Users\\Lenovo\\Documents\\Python\\book\\Python for Data Analysis\\pydata-book'

In [47]:
'555\n555'

'555\n555'

In [49]:
'666\\n666'

'666\\n666'

In [40]:
print('555\n555')
print('666\\n666')

555
555
666\n666

In [53]:
print('555\n555'[2])
print('555\n555'[3])
print('555\n555'[4])

5


5

In [52]:
print('666\\n666'[2])
print('666\\n666'[3])
print('666\\n666'[4])

6
\
n

In [2]:
print('string')
'string'

string

'string'

# บท 4

## Basic Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]

#As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated (or broadcasted henceforth) to the entire selection.
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
l = list(range(10))
l[5:8] = [12]
l

[0, 1, 2, 3, 4, 12, 8, 9]

## Boolean Indexing

In [6]:
a = 1; b = 2;
if (a == 1) & (b == 2):
    print('T & T')
if (a == 1) & (b == 0):
    print('T & F')
if (a == 0) & (b == 2):
    print('F & T')
if (a == 0) & (b == 0):
    print('F & F')

if (a == 1) | (b == 2):
    print('T | T')
if (a == 1) | (b == 0):
    print('T | F')
if (a == 0) | (b == 2):
    print('F | T')
if (a == 0) | (b == 0):
    print('F | F')

T & T
T | T
T | F
F | T

In [19]:
# ข้อควรระวังในการใช้ --> ต้องใส่วงเล็บ
if a == 9 & a == 1:
    print('F & T')
if  (a == 9) & (a == 1):
    print('(F) & (T)')

F & T

In [21]:
np.array([True, False]) | True

array([ True,  True])

In [22]:
np.array([True, False]) | False

array([ True, False])

In [23]:
np.logical_and(np.array([True, False]), False)

array([False, False])

## Array-Oriented Programming with Arrays

In [27]:
p = np.arange(0,1, 0.1)
print(p, len(p)) # ถ้า tick ไปถึง 1 len ก็จะเป็น 11

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] 10

In [29]:
points = np.arange(-5, 5, 0.01)
points[-3:] # tick วิ่งไม่ถึง 5

array([4.97, 4.98, 4.99])

# บท 5

In [1]:
import pandas as pd
import numpy as np

## DataFrame

In [10]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [11]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
three  2002    Ohio  3.6  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False
six    2003  Nevada  3.2  NaN    False

จะทำให้ดีกว่าข้างบน โดยใช้ in ('Ohio',)

In [12]:
bool_series = frame2.state.map(lambda s: s in ('Ohio',))
bool_series

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [13]:
frame2['eastern_2'] = bool_series
frame2

       year   state  pop debt  eastern  eastern_2
one    2000    Ohio  1.5  NaN     True       True
two    2001    Ohio  1.7  NaN     True       True
three  2002    Ohio  3.6  NaN     True       True
four   2001  Nevada  2.4  NaN    False      False
five   2002  Nevada  2.9  NaN    False      False
six    2003  Nevada  3.2  NaN    False      False

# บท 7

In [4]:
import pandas as pd
import numpy as np
from numpy import nan as NA

## Filtering Out Missing Data

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
data[4] = NA

In [6]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [7]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

จะ reimplement ให้เหมือน cell ข้างบนโดยใช้ numpy.all

In [33]:
data_arr = data.values
flag = pd.isnull(data).values
mask = ~flag.all(axis=0) # columns are retained

ans01 = data_arr[:, mask]
print(ans01)

ans02 = data.loc[:, mask]
ans02

[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

## Scratchpad

In [14]:
flag

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [18]:
flag.all(axis=0)

array([False, False, False,  True])

In [20]:
mask

array([ True,  True,  True, False])

จากที่ลองเล่นใน chap 05 "selecting data with a boolean array" จะเป็นการเลือก row
![](df_bool_sel_row.png)

In [24]:
print(data_arr)
print(data_arr[:, mask])

[[1.  6.5 3.  nan]
 [1.  nan nan nan]
 [nan nan nan nan]
 [nan 6.5 3.  nan]]
[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]

In [32]:
data.loc[:, mask]
data.iloc[:, mask]

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

## Filling In Missing Data

จะทำการ fill missing value ด้วย mean*100 เวลา data frame มีหลาย columns

In [76]:
np.random.seed(12345)

col1 = np.random.randn(10, 1)*0.5 + 5
col2 = np.random.randn(10, 1)*0.1 + 3
cols = np.hstack((col1, col2))
# cols[[4, 9]][:, [0, 1]] = np.nan # ถ้าใช้แบบนี้ original cols ไม่ถูก affected
cols[[4, 9]] = np.nan

data = pd.DataFrame(cols, columns=['X1', 'X2'])
mseries = data.apply(lambda x: x.mean(), axis=0)
mseries *= 100

data.fillna(mseries.to_dict())

           X1          X2
0    4.897646    3.100719
1    5.239472    2.870378
2    4.740281    3.027499
3    4.722135    3.022891
4  510.850932  300.496059
5    5.696703    3.088643
6    5.046454    2.799836
7    5.140873    2.962816
8    5.384511    3.166903
9  510.850932  300.496059

In [51]:
np.random.randn?

### Scratchpad

In [35]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_vstack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result_vstack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]

In [37]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_hstack = np.hstack((
                            arr1[:, np.newaxis], 
                            arr2[:, np.newaxis]
                         ))
print("Horizontal Stack:\n", result_hstack)

Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]

In [71]:
cols

array([[4.89764617, 3.10071894],
       [5.23947167, 2.87037789],
       [4.74028064, 3.02749916],
       [4.72213485, 3.02289129],
       [       nan,        nan],
       [5.69670292, 3.08864293],
       [5.04645394, 2.79983627],
       [5.14087308, 2.96281575],
       [5.38451128, 3.16690253],
       [       nan,        nan]])

In [56]:
cols[[4, 9]][:, [0, 1]]

array([[5.98289029, 3.13529168],
       [5.62321737, 2.95614303]])

In [72]:
data

         X1        X2
0  4.897646  3.100719
1  5.239472  2.870378
2  4.740281  3.027499
3  4.722135  3.022891
4       NaN       NaN
5  5.696703  3.088643
6  5.046454  2.799836
7  5.140873  2.962816
8  5.384511  3.166903
9       NaN       NaN

In [75]:
mseries

X1    510.850932
X2    300.496059
dtype: float64

## Computing Indicator/Dummy Variables
จะทำการทดสอบ สิ่งที่อยากรู้ ต่อไปนี้

1. Python break จากลูปได้มั้ย
2. ทดสอบว่าทั้ง series เป็นจริง ด้วย all ได้หรือไม่
3. ถ้า access df.iloc[i, [0, 1, 2]] จะได้ DataFrame หรือ Series?
4. ทดสอบว่าสอง DataFrame เท่ากันทำยังไง

In [15]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('../datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)
movies[:3]

C:\Users\Lenovo\miniconda3\envs\4book\lib\site-packages\pandas\io\parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())

   movie_id                    title                        genres
0         1         Toy Story (1995)   Animation|Children's|Comedy
1         2           Jumanji (1995)  Adventure|Children's|Fantasy
2         3  Grumpier Old Men (1995)                Comedy|Romance

In [16]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [18]:
#scratchpad
np.where(genres == 'Comedy')

(array([2], dtype=int64),)

In [22]:
#scratchpad
a1 = np.array([2])
a2 = np.array([4, 8, 16])
a3 = np.array([32, 64])
a1

array([2])

In [23]:
#scratchpad
np.concatenate([a1, a2, a3])

array([ 2,  4,  8, 16, 32, 64])

In [17]:
#scratchpad
l = ['Comedy', 'Fantasy', 'Romance']
li = [np.where(genres == e)[0] for e in l] # np.where คืน result เป็น tuple of array เราต้องแกะออกมาหนึ่งชั้นให้เป็น array เฉยๆ
np.concatenate(li)

array([2, 4, 5], dtype=int64)

In [111]:
def findIndex(l):
    return np.concatenate([np.where(genres == e)[0] for e in l])

In [112]:
#scratchpad
findIndex('Comedy|Romance'.split('|'))

array([2, 5], dtype=int64)

### บททดสอบ 1

In [79]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [116]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|')) # วิธีจากหนังสือ
    my_indices = findIndex(gen.split('|'))
    if i < 5:
        print(f"indices:{indices}\nmy_indices:{my_indices}")
    if not np.array_equal(indices, my_indices):
        print('Different indices found!')
        break

indices:[0 1 2]
my_indices:[0 1 2]
indices:[3 1 4]
my_indices:[3 1 4]
indices:[2 5]
my_indices:[2 5]
indices:[2 6]
my_indices:[2 6]
indices:[2]
my_indices:[2]

#### Scratchpad

In [24]:
ind=np.where([[False, False, True],[False, False, True]]) # เอา tuples ที่ return มา ทำ fancy indexing กันจะได้ ตำแหน่งที่เป็น True
ind

(array([0, 1], dtype=int64), array([2, 2], dtype=int64))

In [28]:
ar=np.arange(6).reshape(2, 3)
print(ar)
ar[ind[0], ind[1]]

[[0 1 2]
 [3 4 5]]

array([2, 5])

In [108]:
dummies.columns.get_indexer('Comedy|Romance'.split('|'))

array([2, 5], dtype=int64)

### บททดสอบ 2

In [119]:
test = pd.Series([False]*len(movies.genres))

for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|')) # วิธีจากหนังสือ
    my_indices = findIndex(gen.split('|'))
    test[i] = np.array_equal(indices, my_indices)

In [134]:
test.all()

True

### บททดสอบ 3

In [127]:
movies.iloc[[2], 1:]

                     title          genres
2  Grumpier Old Men (1995)  Comedy|Romance

In [129]:
#mix #lower
movies.iloc[2, 1:]

title     Grumpier Old Men (1995)
genres             Comedy|Romance
Name: 2, dtype: object

### บททดสอบ 4

See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html