In [1]:
a = 1
b = 1
a is b

True

In [2]:
a = [1]
b = [1]
a is b

False

In [6]:
x = ([1,1],[2,2])
y = x*2
print(y)
y[2] is x[0]

([1, 1], [2, 2], [1, 1], [2, 2])

True

In [8]:
x = ([1,1],[2,2],[2,2])
y = x*5
print(y)
print(y[12] is x[0]) #12 = 0 mod 3
print(y[10] is x[1]) #10 = 1 mod 3

([1, 1], [2, 2], [2, 2], [1, 1], [2, 2], [2, 2], [1, 1], [2, 2], [2, 2], [1, 1], [2, 2], [2, 2], [1, 1], [2, 2], [2, 2])
True
True

In [3]:
import numpy as np
import pandas as pd

pd.DataFrame([[1, 2], [10, 20], [100, 200]])

     0    1
0    1    2
1   10   20
2  100  200

In [4]:
pd.DataFrame(zip([1, 10, 100], [2, 20, 200]))

     0    1
0    1    2
1   10   20
2  100  200

In [5]:
pd.DataFrame(np.array([[1, 2], [10, 20], [100, 200]]))

     0    1
0    1    2
1   10   20
2  100  200

In [4]:
import pandas as pd

pd.DataFrame([{'a': [1, 2, 3]}]) 
# label ของ dict อยากให้มันเป็น row label แต่มันเป็น col label
# สาเหตุที่อยากเพราะ อยากลอง implement groupby.mean() from scratch 
# เพราะคิดว่าสามารถสร้าง pair ของ name + processed_group ซึ่งคาดหวังว่า ถ้าสามารถจับมันใส่ {pair: processed_group} แล้วเอามาต่อๆกัน
# ก่อนป้อนเข้า instructor ของ DataFrame ได้ก็คงดี

           a
0  [1, 2, 3]

In [7]:
pd.DataFrame([{'a': 1, 'b': 2, 'c': 3}])

   a  b  c
0  1  2  3

In [6]:
pd.DataFrame({'a': {'one': [1, 2, 3]}}) # สิ่งที่อยากให้เป็น row ถูกบังคับให้อยู่ใน column a ทั้งหมด ทำให้ไม่แยกตัวเป็นหนึ่ง row ที่มีหลายๆคอลัมน์

             a
one  [1, 2, 3]